In [ ]:
list---values with different datatype
arrays--values with same data type

In [1]:
import numpy
import numpy as np
from numpy import *

In [6]:
list=[1,2,3,4]
list

[1, 2, 3, 4]

In [3]:
type(list)

list

In [9]:
arr=array(list)

In [10]:
arr

array([1, 2, 3, 4])

In [ ]:
1.import numpy
numpy.namespace
numpy.array()
numpy.arange()

2.import numpy as np
np.namespace
np.array()
np.arange()


3.from numpy import *

namespace
array()
arange()

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr

array([1, 2, 3, 4])

In [13]:
arr.shape

(4,)

In [ ]:
1
2
3
4

1 2 3 4


In [14]:
arr.ndim

1

In [15]:
arr.size

4

In [17]:
z=np.zeros(10)

In [19]:
type(z)

numpy.ndarray

In [20]:
o=ones(10)

In [21]:
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
o.ndim

1

In [24]:
o.shape

(10,)

### 2 d arrays

In [30]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[3,4,5]])

In [31]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 4, 5]])

In [32]:
x.ndim

2

In [33]:
x.shape

(4, 3)

In [ ]:
create a 6*5 matrix which should contain elements from 30 to 60

In [34]:
p=np.array([[31,32,33,34,35],[34,35,36,37,38],[45,47,48,49,40],[50,51,52,55,54],[31,32,33,34,35],[31,32,43,54,55]])


In [35]:
p

array([[31, 32, 33, 34, 35],
       [34, 35, 36, 37, 38],
       [45, 47, 48, 49, 40],
       [50, 51, 52, 55, 54],
       [31, 32, 33, 34, 35],
       [31, 32, 43, 54, 55]])

In [36]:
p.shape

(6, 5)

In [37]:
p.reshape(5,6)

array([[31, 32, 33, 34, 35, 34],
       [35, 36, 37, 38, 45, 47],
       [48, 49, 40, 50, 51, 52],
       [55, 54, 31, 32, 33, 34],
       [35, 31, 32, 43, 54, 55]])

In [38]:
p.size

30

In [ ]:
30----5*6,6*5,3*10,10*3,2*15,15*2

### 3d arrays

In [39]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 4, 5]])

In [40]:
x=x.reshape(3,2,2)

In [41]:
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 3],
        [4, 5]]])

In [42]:
x.ndim

3

In [43]:
x.shape

(3, 2, 2)

In [44]:
x.size

12

### Indexing

In [45]:
#accessing 1 d array
arr=np.array([1,2,3,4])

In [46]:
arr

array([1, 2, 3, 4])

In [48]:
arr[1]

2

In [49]:
arr[1]+arr[2]

5

In [50]:
#access 2 d arrays
a=np.array([[1,2,3,4],[2,3,4,5]])

In [51]:
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [56]:
print("2 nd element on 1 st dim",a[0,1])

2 nd element on 1 st dim 2


In [58]:
print("3 rd element on 2 st dim",a[1,2])

3 rd element on 2 st dim 4


In [59]:
np.linspace(0,10,5)
#np.linspace(start,end,no,of values start and end)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [61]:
np.linspace(0,20,15)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

In [62]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
np.random.randint(0,10,10)
#np.random.randint(start,end,no,of values start and end)

array([2, 5, 8, 7, 6, 0, 7, 6, 3, 9])

In [64]:
np.random.rand(3,3)

array([[0.45909644, 0.08264151, 0.72247802],
       [0.75424538, 0.48436811, 0.15235388],
       [0.55463307, 0.48064451, 0.40729155]])

In [65]:
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [66]:
a.max()

5

In [67]:
a.min()

1

In [69]:
x.argmax()

8

In [71]:
x.argmin()

0

In [ ]:
create a linearly spaced array with two elements in it


In [78]:
np.arange(0,11,3)

array([0, 3, 6, 9])

### slicing

In [ ]:
indexing---one value
slicing---piece of elements,multiple elements

In [79]:
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [81]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [82]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
a[0,0:2]

array([1, 2])

In [84]:
a[0,:2]

array([1, 2])

In [85]:
a[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [86]:
a[1:3,1:3]


array([[5, 6],
       [8, 9]])

In [87]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
#rows,columns
a[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [93]:
a[0:2,0:]


array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
# addition possible--yes
x=np.arange(0,10,2)

In [95]:
x

array([0, 2, 4, 6, 8])

In [96]:
y=np.arange(0,10,2)

In [98]:
z=x+y

In [99]:
z

array([ 0,  4,  8, 12, 16])

In [100]:
np.sqrt(x)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712])

In [101]:
np.exp(z)

array([1.00000000e+00, 5.45981500e+01, 2.98095799e+03, 1.62754791e+05,
       8.88611052e+06])

In [102]:
np.sin(z)

array([ 0.        , -0.7568025 ,  0.98935825, -0.53657292, -0.28790332])

In [122]:
x=np.arange(0,10,2)
x

array([0, 2, 4, 6, 8])

In [123]:
ar=x.copy()

In [124]:
ar

array([0, 2, 4, 6, 8])

In [125]:
x[0]=25
x

array([25,  2,  4,  6,  8])

In [126]:
x

array([25,  2,  4,  6,  8])

In [127]:
ar

array([0, 2, 4, 6, 8])

In [128]:
y=ar.view()

In [129]:
y

array([0, 2, 4, 6, 8])

In [130]:
ar

array([0, 2, 4, 6, 8])

In [131]:
ar[1]=90

In [132]:
ar

array([ 0, 90,  4,  6,  8])

In [113]:
y

array([25, 90,  4,  6,  8])

In [ ]:
copy-----changes in parent will not reflect in child
view==changes in parent will be reflected in child

In [ ]:
create an array of 5 *5 shape whcih contains numbers from 0 to 24
0 1 2 3 4 
5 6  8 9 10
11 12 13 14 15 
16 17 18 19 20 
21 22 23 24 25


2 3 4 
8 9 10
13 14 15 
18 19 20 
23 24 25

In [114]:
a =np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]])


In [115]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [117]:
a[0:,2:]


array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])